### ISSUE TITLE
Projects not shown in menu

### ISSUE THREAD

**Issue by n1trux** [andresth/Kandroid#36]
### Actual behaviour

When I open the menu, the projects aren't shown.

### Expected behaviour

Some older version before 0.5 displayed the projects.

### Steps to reproduce

Open Menu, projects not there. Screenshot:

![kandroid-screenshot](https://user-images.githubusercontent.com/7255542/32298604-06c9c85c-bf53-11e7-9689-19a882fee5a2.jpg)

### Configuration

- Kandroid version: 0.5.7 (from F-Droid)
- Android version: 6.0.1, 7.0
- Device type, name and manufacturer: Google Nexus 5, Sony Z3 Compact
- Kanboard version: 1.0.46

**Comment by lyan2k** [comment]
I have the same issue, is it a kandroid issue or a kanboard issue ?

**Comment by n1trux** [comment]
I suppose it's a Kandroid issue due to the API/Webhook changes in Kanboard.

Testing multiple old versions of Kanboard with the newest Kandroid might shed some light on this.

**Comment by dvdcr** [comment]
I had the same problem. Making son tests, the problem occurs when you haven't installed calendar-plugin because calendar url is not send in the JSON response and the app fails. 
A workaround in my case is installing calendar-plugin. ¿Have you installed than plugin?
In my case I solved the problem making some changes in 
 app/src/main/java/in/andres/kandroid/kanboard/KanboardProject.java to check if the URL whas present en the response.
